spring:
  application:
    name: nasa-asteroid-api
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
nasa:
  api:
    api-key: ${NASA_API_KEY:DEMO_KEY}
    base-url: ${NASA_BASE_URL:https://api.nasa.gov}
